### ISSUE TITLE
PROJECT: Andrew Panzl

### ISSUE THREAD

**Issue by appanzl** [laboon/Capstone_Spring2018#35]
1. NetApp
2. OCCAM experimenting with Arduino/Rasp Pi.
3. Viz 

Personal preference, I'd like to be working with an industry partner, selfishly want to network and gain the professional exposure. I love lower level programming languages, happily prefer C/C++ over Java. NetApp sounds like it would extend CS1550, the course was personally challenging and I'd like to keep up with that challenge by learning some more implementations surrounding Operating Systems. OCCAM w/ Rasp Pi would be a wonderful excuse to learn how to mess with Raspberry Pi's. Viz would be an implementation of data structures which I highly enjoy. I took a course with Pr. Bigrigg and he's a hoot, I would love to continue working under his supervision.

**Comment by laboon** [comment]
Andrew, would you be interested in the hardware/software interface project?  You'd be working directly with an engineer in industry and learning about low-level code.
